//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace God {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("God.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возраст.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Средняя оценка.
        /// </summary>
        public static string AvgScore {
            get {
                return ResourceManager.GetString("AvgScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string BotanColor {
            get {
                return ResourceManager.GetString("BotanColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ботаны.
        /// </summary>
        public static string Botans {
            get {
                return ResourceManager.GetString("Botans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ура! Ребёнок .
        /// </summary>
        public static string ChildBorn {
            get {
                return ResourceManager.GetString("ChildBorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество детей.
        /// </summary>
        public static string ChildrenCount {
            get {
                return ResourceManager.GetString("ChildrenCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkGreen.
        /// </summary>
        public static string CoolParentColor {
            get {
                return ResourceManager.GetString("CoolParentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Крутые предки.
        /// </summary>
        public static string CoolParents {
            get {
                return ResourceManager.GetString("CoolParents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Симпатия не взаимна :&apos;(.
        /// </summary>
        public static string DontLike {
            get {
                return ResourceManager.GetString("DontLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Женщина.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пол.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magenta.
        /// </summary>
        public static string Girl {
            get {
                return ResourceManager.GetString("Girl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добрый день. Вы используете консоль бога.
        ///Сколько людей вы хотите сотворить?.
        /// </summary>
        public static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравствуйте!.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы ввели некорректное число. Попробуйте еще раз.
        /// </summary>
        public static string InputError {
            get {
                return ResourceManager.GetString("InputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мужчина.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество денег.
        /// </summary>
        public static string MoneyAmount {
            get {
                return ResourceManager.GetString("MoneyAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkRed.
        /// </summary>
        public static string MoneyBackgroundColor {
            get {
                return ResourceManager.GetString("MoneyBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to totalMoney.txt.
        /// </summary>
        public static string OutputFileName {
            get {
                return ResourceManager.GetString("OutputFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkGray.
        /// </summary>
        public static string PairBackgroundColor {
            get {
                return ResourceManager.GetString("PairBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkBlue.
        /// </summary>
        public static string ParentColor {
            get {
                return ResourceManager.GetString("ParentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Родители.
        /// </summary>
        public static string Parents {
            get {
                return ResourceManager.GetString("Parents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество.
        /// </summary>
        public static string Patronymic {
            get {
                return ResourceManager.GetString("Patronymic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите Enter чтобы устроить свиданку,
        ///Q или Escape чтобы покинуть нас..
        /// </summary>
        public static string PressButton {
            get {
                return ResourceManager.GetString("PressButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одинаковый пол!.
        /// </summary>
        public static string SameGenderError {
            get {
                return ResourceManager.GetString("SameGenderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string StudentColor {
            get {
                return ResourceManager.GetString("StudentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Суденты.
        /// </summary>
        public static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извините, сегодня воскресение. Сотворить людей не получится!.
        /// </summary>
        public static string SundayError {
            get {
                return ResourceManager.GetString("SundayError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to находящийся рядом с исполняемым файлом
        ///и содержит суммарные деньги крутых предков..
        /// </summary>
        public static string TotalMoneyGreeting {
            get {
                return ResourceManager.GetString("TotalMoneyGreeting", resourceCulture);
            }
        }
    }
}
